server:
  port: 8061

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/deliverytogo_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8751/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: aVeryStrongSecretKeyThatIsAtLeast256BitsLongForHS256
  expiration: 86400000
