server:
  port: 8751

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# ⛔ Prevents Eureka client auto-registration from being created
spring.cloud:
  service-registry:
    auto-registration:
      enabled: false
